<?php

/**
 * Plugin Name: My custom Website Blocks
 * Description: A component-based website builder built from scratch.
 * Version: 1.0.0
 * Author: Kestas
 */

if ( ! defined( 'ABSPATH' ) ) exit;

/**
 * Register the blocks using the build folder
 */
function create_custom_blocks_init() {
    
    /**
     * Part 1: Asset Metadata
     * The 'index.asset.php' file is automatically generated by @wordpress/scripts.
     * It contains an array of dependencies (like 'wp-blocks', 'wp-element') and
     * a version hash based on the current file content for cache-busting.
     */
    $asset_file = include( __DIR__ . '/build/index.asset.php' );

    /**
     * Part 2: Register Global Styles
     * Since we are using a centralized build (src/index.js), WebPack bundles
     * all block CSS into two main files in the root of the /build folder.
     */

    // Register the frontend styles (style-index.css)
    wp_register_style(
        'my-blocks-style',                                  // Unique Handle
        plugins_url( 'build/style-index.css', __FILE__ ),   // Path to the file
        array(),                                            // Dependencies
        $asset_file['version']                              // Version for cache-busting
    );

    // Register the editor-only styles (index.css)
    // This usually contains the "admin-only" visual hints like dashed borders.
    wp_register_style(
        'my-block-editor-style',
        plugins_url( 'build/index.css', __FILE__ ),
        array(),
        $asset_file['version']
    );

    /**
     * Part 3: Block Registration Loop
     * Instead of repeating code for every block, we define an array of our
     * block folder names and loop through them
     */
    $blocks = [
        'hero',
        'site-header',
        'feature-grid',
        'feature-item'
    ];

    foreach ( $blocks as $block ) {
        /**
         * register_block_type() read the block.json in each folder.
         * We override the 'style' and 'editor_style' settings here to point
         * to the global handles we registered in Part 2.
         */
        register_block_type( __DIR__ . '/build/blocks/' . $block, array(
            'style' => 'my-blocks-style',               // Loads on frontend + editor
            'editor_style' => 'my-blocks-editor-style'  // Loads in editor only
        ) );
    }
}

// Hook the function into WordPress initialization
add_action( 'init', 'create_custom_blocks_init' );